/// Flutter icons MyIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
import 'package:flutter/widgets.dart';

const String _kFontFam = 'MyIcons';
const String? _kFontPkg = null;

class MyIcons {
  IconData get firebase_plain =>
      const IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData get go_original =>
      const IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData get vuejs_original =>
      const IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData get flutter_original =>
      const IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData get twitter =>
      const IconData(0xf099, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData get github =>
      const IconData(0xf09b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData get linkedin_in =>
      const IconData(0xf0e1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  IconData get stack_overflow =>
      const IconData(0xf16c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
