name: personal_portfolio
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <3.1.0"

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.1
  flutter_devicon: ^1.0.1
  layout: ^1.0.3
  provider: ^6.0.5
  routemaster: ^1.0.1
  google_fonts: ^4.0.3
  material_color_utilities: ^0.2.0
  shared_preferences: ^2.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0
  flutter_launcher_icons: ^0.12.0
  ficcanaso: ^5.0.0+1
  game_of_life: 
    git: https://github.com/GangemiLorenzo/Game-Of-Life

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/profile/
    - assets/fonts/
    - assets/projects/

  fonts:
    - family: MyIcons
      fonts:
      - asset: assets/fonts/MyIcons.ttf

flutter_gen:
  output: lib/gen/