name: personal_portfolio
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0-56.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.0
  layout: ^1.0.2
  modal_bottom_sheet: ^2.0.0
  routemaster: ^0.10.0-dev5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  flutter_gen_runner: ^4.1.2
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.2
  golden_toolkit: ^0.12.0

flutter:
  uses-material-design: true