name: Gh-Pages

## Trigger the action on push to main branch
on:
  push:
    branches: [main]

jobs:
  ## Got one job named build, it runs on ubuntu-latest
  build:
    runs-on: ubuntu-latest

    steps:
      ## Checkout the code from the repository into $GITHUB_WORKSPACE
      - uses: actions/checkout@v4
      ## Set up the flutter environment from the stable channel
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      ## Build the web version of the app and releases it on gh-pages
      - uses: bluefireteam/flutter-gh-pages@v8
        with:
          webRenderer: canvaskit
